[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#38BDF8"
backgroundColor = "#0A1128"
secondaryBackgroundColor = "#111E38"
textColor = "#E2E8F0"
